version: "3.8"
services:
  database-postgres: 
   image: postgres:14.2
   environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
   ports:
      - '5432:5432'
   volumes: 
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local
